# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93683506d29b333db5dbe6456705cf279ef2a618918c67620df928384bc7bf6eed752d186b9325c06749f9f3297fa8b0b725ddec115a5bf5f663a91f10b89623

test:
  secret_key_base: f527dd1611953269f5f1d8c3436cdbc414040433d52eb10dbeb29bcc483155b8ce344363c2e30507166d38617e03a1d8d745905278c66d9ec2da2ccc45692002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
